//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefDepGuard.Applied.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefDepGuard.Applied.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this reference through the solution explorer.
        /// </summary>
        internal static string Action_Add_String {
            get {
                return ResourceManager.GetString("Action_Add_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this reference through the solution explorer.
        /// </summary>
        internal static string Action_Remove_String {
            get {
                return ResourceManager.GetString("Action_Remove_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; for project &apos;.
        /// </summary>
        internal static string For_Project_String {
            get {
                return ResourceManager.GetString("For_Project_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of global level .
        /// </summary>
        internal static string Global_Level {
            get {
                return ResourceManager.GetString("Global_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no required.
        /// </summary>
        internal static string No_Required_String {
            get {
                return ResourceManager.GetString("No_Required_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  reference .
        /// </summary>
        internal static string Reference_String {
            get {
                return ResourceManager.GetString("Reference_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of solution level.
        /// </summary>
        internal static string Solution_Level {
            get {
                return ResourceManager.GetString("Solution_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unacceptable.
        /// </summary>
        internal static string Unacceptable_String {
            get {
                return ResourceManager.GetString("Unacceptable_String", resourceCulture);
            }
        }
    }
}
