//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefDepGuard.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefDepGuard.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension activation fail: During activation there wasn&apos;t detected any references between projects.
        /// </summary>
        internal static string Activation_Fail {
            get {
                return ResourceManager.GetString("Activation_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension is successfully activated.
        /// </summary>
        internal static string Activation_Success {
            get {
                return ResourceManager.GetString("Activation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference commit fail:
        ///During commit there wasn&apos;t detected any references between projects.
        /// </summary>
        internal static string Commit_Fail {
            get {
                return ResourceManager.GetString("Commit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The references are committed successfully.
        /// </summary>
        internal static string Commit_Success {
            get {
                return ResourceManager.GetString("Commit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Error text: .
        /// </summary>
        internal static string Error_Text_Title {
            get {
                return ResourceManager.GetString("Error_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefDepGuard.
        /// </summary>
        internal static string Extension_Name {
            get {
                return ResourceManager.GetString("Extension_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension isn&apos;t load yet.
        ///Wait until the load ends to pass the action.
        /// </summary>
        internal static string Extension_Not_Load_Yet {
            get {
                return ResourceManager.GetString("Extension_Not_Load_Yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global config file parse.
        /// </summary>
        internal static string Global_Config_File_String {
            get {
                return ResourceManager.GetString("Global_Config_File_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTML export ended with fail as the file is occupied by different process. Try again later.
        /// </summary>
        internal static string Graph_Type_Export_Fail {
            get {
                return ResourceManager.GetString("Graph_Type_Export_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTML export ended successfully.
        ///Open a folder with the generated report?.
        /// </summary>
        internal static string Graph_Type_Export_Success {
            get {
                return ResourceManager.GetString("Graph_Type_Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to HTML.
        /// </summary>
        internal static string Graph_Type_Export_Title {
            get {
                return ResourceManager.GetString("Graph_Type_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution config file parse.
        /// </summary>
        internal static string Solution_Config_File_String {
            get {
                return ResourceManager.GetString("Solution_Config_File_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XLSX report ended with fail as the file is occupied by different process. 
        ///Close all Excel files and try again later.
        /// </summary>
        internal static string Table_Type_Export_Fail {
            get {
                return ResourceManager.GetString("Table_Type_Export_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XLSX export successfully ended.
        ///Open a folder with the generated report?.
        /// </summary>
        internal static string Table_Type_Export_Success {
            get {
                return ResourceManager.GetString("Table_Type_Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XLSX.
        /// </summary>
        internal static string Table_Type_Export_Title {
            get {
                return ResourceManager.GetString("Table_Type_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start an export as the extension didn&apos;t detect any project references in this solution.
        /// </summary>
        internal static string Unable_To_Export_Message {
            get {
                return ResourceManager.GetString("Unable_To_Export_Message", resourceCulture);
            }
        }
    }
}
