//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefDepGuard.UI.Resources.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefDepGuard.UI.Resources.StringResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the reference through the 
        ///solution explorer.
        /// </summary>
        internal static string Action_Add_String {
            get {
                return ResourceManager.GetString("Action_Add_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action file.
        /// </summary>
        internal static string Action_File_Title {
            get {
                return ResourceManager.GetString("Action_File_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename project in config file with rules remain?.
        /// </summary>
        internal static string Action_On_Project_Rename {
            get {
                return ResourceManager.GetString("Action_On_Project_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the reference through the 
        ///solution explorer.
        /// </summary>
        internal static string Action_Remove_String {
            get {
                return ResourceManager.GetString("Action_Remove_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension activation fail: During activation there wasn&apos;t detected any references between projects.
        /// </summary>
        internal static string Activation_Fail {
            get {
                return ResourceManager.GetString("Activation_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension is successfully activated.
        /// </summary>
        internal static string Activation_Success {
            get {
                return ResourceManager.GetString("Activation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference is claimed as the required and 
        ///unacceptable at the same time.
        /// </summary>
        internal static string Claim_Match_Error_Description {
            get {
                return ResourceManager.GetString("Claim_Match_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference commit fail:
        ///During commit there wasn&apos;t detected any references between projects.
        /// </summary>
        internal static string Commit_Fail {
            get {
                return ResourceManager.GetString("Commit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The references are committed successfully.
        /// </summary>
        internal static string Commit_Success {
            get {
                return ResourceManager.GetString("Commit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .
        /// </summary>
        internal static string Config_File_Load_Error {
            get {
                return ResourceManager.GetString("Config_File_Load_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config file load ended with fail.
        /// </summary>
        internal static string Config_File_Load_Error_1 {
            get {
                return ResourceManager.GetString("Config_File_Load_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Error: config file load failed.
        /// </summary>
        internal static string Config_File_load_Error_Title {
            get {
                return ResourceManager.GetString("Config_File_load_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache file data load ends with fail.
        /// </summary>
        internal static string Config_File_Load_From_Cache_Fail {
            get {
                return ResourceManager.GetString("Config_File_Load_From_Cache_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .
        /// </summary>
        internal static string Config_File_Not_Found_Error {
            get {
                return ResourceManager.GetString("Config_File_Not_Found_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config file not found.
        /// </summary>
        internal static string Config_File_Not_Found_Error_1 {
            get {
                return ResourceManager.GetString("Config_File_Not_Found_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file will be recreated with the usage of default sample.
        /// </summary>
        internal static string Config_File_On_Create_From_Sample_Action {
            get {
                return ResourceManager.GetString("Config_File_On_Create_From_Sample_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate config file by the usage of default file sample?.
        /// </summary>
        internal static string Config_File_On_Create_From_Sample_Question {
            get {
                return ResourceManager.GetString("Config_File_On_Create_From_Sample_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file will be recreated with the latest cache data.
        /// </summary>
        internal static string Config_File_On_Load_From_Cache_Action {
            get {
                return ResourceManager.GetString("Config_File_On_Load_From_Cache_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate config file by the last saved cache instance? .
        /// </summary>
        internal static string Config_File_On_Load_From_Cache_Question {
            get {
                return ResourceManager.GetString("Config_File_On_Load_From_Cache_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check it on syntax errors 
        ///and for compliance with the configuration file template.
        /// </summary>
        internal static string Config_File_Property_Null_Error_Action {
            get {
                return ResourceManager.GetString("Config_File_Property_Null_Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not contains property 
        ///&apos;.
        /// </summary>
        internal static string Config_File_Property_Null_Error_Message {
            get {
                return ResourceManager.GetString("Config_File_Property_Null_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config file.
        /// </summary>
        internal static string Config_File_String_2 {
            get {
                return ResourceManager.GetString("Config_File_String_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data from the file will be transferred to rollback-file.
        /// </summary>
        internal static string Config_File_Transfer_To_Rollback_File_Message {
            get {
                return ResourceManager.GetString("Config_File_Transfer_To_Rollback_File_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.
        /// </summary>
        internal static string Config_File_Type_Prefix_Global {
            get {
                return ResourceManager.GetString("Config_File_Type_Prefix_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution.
        /// </summary>
        internal static string Config_File_Type_Prefix_Solution {
            get {
                return ResourceManager.GetString("Config_File_Type_Prefix_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains value 
        ///&apos;.
        /// </summary>
        internal static string Contains_Value_String {
            get {
                return ResourceManager.GetString("Contains_Value_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count_Title {
            get {
                return ResourceManager.GetString("Count_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description_Title {
            get {
                return ResourceManager.GetString("Description_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected unacceptable references.
        /// </summary>
        internal static string Detected_Unacceptable_Refs_Title {
            get {
                return ResourceManager.GetString("Detected_Unacceptable_Refs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; of the eponymous parameter .
        /// </summary>
        internal static string Eponymous_Parameter_String {
            get {
                return ResourceManager.GetString("Eponymous_Parameter_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error level.
        /// </summary>
        internal static string Error_Level_Title {
            get {
                return ResourceManager.GetString("Error_Level_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Error text: .
        /// </summary>
        internal static string Error_Text_Title {
            get {
                return ResourceManager.GetString("Error_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error type.
        /// </summary>
        internal static string Error_Type_Title {
            get {
                return ResourceManager.GetString("Error_Type_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no any reference changes from the last state commit .
        /// </summary>
        internal static string Excecute_Changed_Refs_On_Empty {
            get {
                return ResourceManager.GetString("Excecute_Changed_Refs_On_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are following reference changes since the last state commit :
        ///.
        /// </summary>
        internal static string Excecute_Changed_Refs_Start_Message {
            get {
                return ResourceManager.GetString("Excecute_Changed_Refs_Start_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project references changes.
        /// </summary>
        internal static string Excecute_Changed_Refs_Title {
            get {
                return ResourceManager.GetString("Excecute_Changed_Refs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no any project references in this solution at this moment.
        /// </summary>
        internal static string Excecute_Current_Refs_On_Empty {
            get {
                return ResourceManager.GetString("Excecute_Current_Refs_On_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References between projects at this moment.
        /// </summary>
        internal static string Excecute_Current_Refs_Title {
            get {
                return ResourceManager.GetString("Excecute_Current_Refs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added references:.
        /// </summary>
        internal static string Excecute_Refs_Adds_Title {
            get {
                return ResourceManager.GetString("Excecute_Refs_Adds_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Project .
        /// </summary>
        internal static string Excecute_Refs_Project_Title {
            get {
                return ResourceManager.GetString("Excecute_Refs_Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Removed references:.
        /// </summary>
        internal static string Excecute_Refs_Remove_Title {
            get {
                return ResourceManager.GetString("Excecute_Refs_Remove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  exceed.
        /// </summary>
        internal static string Exceed_String {
            get {
                return ResourceManager.GetString("Exceed_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefDepGuard.
        /// </summary>
        internal static string Extension_Name {
            get {
                return ResourceManager.GetString("Extension_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension isn&apos;t load yet.
        ///Wait until the load ends to pass the action.
        /// </summary>
        internal static string Extension_Not_Load_Yet {
            get {
                return ResourceManager.GetString("Extension_Not_Load_Yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config-file.
        /// </summary>
        internal static string Finded_Project_Place_Config {
            get {
                return ResourceManager.GetString("Finded_Project_Place_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution.
        /// </summary>
        internal static string Finded_Project_Place_Solution {
            get {
                return ResourceManager.GetString("Finded_Project_Place_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it needed to use RefDepGuard on.
        /// </summary>
        internal static string First_Solution_Load_Message_1 {
            get {
                return ResourceManager.GetString("First_Solution_Load_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  solution ?.
        ///On click &apos;YES&apos; the extension will be activated and check projects on config file rules compare.
        /// </summary>
        internal static string First_Solution_Load_Message_2 {
            get {
                return ResourceManager.GetString("First_Solution_Load_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first extension load.
        /// </summary>
        internal static string First_Solution_Load_Title {
            get {
                return ResourceManager.GetString("First_Solution_Load_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for a .
        /// </summary>
        internal static string For_string {
            get {
                return ResourceManager.GetString("For_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden reference!.
        /// </summary>
        internal static string Forbidden_Reference_Title {
            get {
                return ResourceManager.GetString("Forbidden_Reference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the project version or modify the 
        ///config file.
        /// </summary>
        internal static string Framework_Version_Comparability_Error_Action {
            get {
                return ResourceManager.GetString("Framework_Version_Comparability_Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;, when its max acceptable version is  &apos;.
        /// </summary>
        internal static string Framework_Version_Comparability_Error_Message {
            get {
                return ResourceManager.GetString("Framework_Version_Comparability_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global config file parse.
        /// </summary>
        internal static string Global_Config_File_String {
            get {
                return ResourceManager.GetString("Global_Config_File_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of global level .
        /// </summary>
        internal static string Global_Level {
            get {
                return ResourceManager.GetString("Global_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTML export ended with fail as the file is occupied by different process. Try again later.
        /// </summary>
        internal static string Graph_Type_Export_Fail {
            get {
                return ResourceManager.GetString("Graph_Type_Export_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTML export ended successfully.
        ///Open a folder with the generated report?.
        /// </summary>
        internal static string Graph_Type_Export_Success {
            get {
                return ResourceManager.GetString("Graph_Type_Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to HTML.
        /// </summary>
        internal static string Graph_Type_Export_Title {
            get {
                return ResourceManager.GetString("Graph_Type_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  have a version 
        ///&apos;.
        /// </summary>
        internal static string Have_Version_String {
            get {
                return ResourceManager.GetString("Have_Version_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the specified
        ///&apos;max_framework_version&apos; string for compliance with the relevant TFM solution.
        /// </summary>
        internal static string Illegal_Template_Usage_Warn_Action {
            get {
                return ResourceManager.GetString("Illegal_Template_Usage_Warn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the &apos;framework_max_version&apos; parameter specifies TFM, which is not found in any of the
        ///&apos;TargetFramework&apos; of this solution projects.
        /// </summary>
        internal static string Illegal_Template_Usage_Warn_Message {
            get {
                return ResourceManager.GetString("Illegal_Template_Usage_Warn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the specified 
        ///&apos;max_framework_version&apos; string for compliance with the relevant TFM project.
        /// </summary>
        internal static string Illegal_TFM_Usage_Error_Action {
            get {
                return ResourceManager.GetString("Illegal_TFM_Usage_Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains an attempt
        /// to set a limit for TFM that is not found in the current project.
        /// </summary>
        internal static string Illegal_TFM_Usage_Error_Message {
            get {
                return ResourceManager.GetString("Illegal_TFM_Usage_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the considered project .
        /// </summary>
        internal static string In_A_Cons_Project_String {
            get {
                return ResourceManager.GetString("In_A_Cons_Project_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside .
        /// </summary>
        internal static string In_Inside_Pretext {
            get {
                return ResourceManager.GetString("In_Inside_Pretext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  inside .
        /// </summary>
        internal static string In_Inside_Pretext_small_letter {
            get {
                return ResourceManager.GetString("In_Inside_Pretext_small_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the name of the project &apos;.
        /// </summary>
        internal static string In_The_Proj_Name_String {
            get {
                return ResourceManager.GetString("In_The_Proj_Name_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the parameter value to a valid one.
        /// </summary>
        internal static string Incorrect_TFM_Usage_Error_Action {
            get {
                return ResourceManager.GetString("Incorrect_TFM_Usage_Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains the use of a template
        /// for setting multiple restrictions, which is unacceptable for this project (the project has only one type of a specified TFM).
        /// </summary>
        internal static string Incorrect_TFM_Usage_Error_Message {
            get {
                return ResourceManager.GetString("Incorrect_TFM_Usage_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  contains 
        ///an incorrect entry of its value.
        /// </summary>
        internal static string Invalid_Project_Type_Error {
            get {
                return ResourceManager.GetString("Invalid_Project_Type_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the higher value of the &apos;framework_max_version&apos; parameter .
        /// </summary>
        internal static string Max_Fr_Version_Conflict_Bigger_Value_Error_Cause {
            get {
                return ResourceManager.GetString("Max_Fr_Version_Conflict_Bigger_Value_Error_Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the value to the correct 
        ///format.
        /// </summary>
        internal static string Max_Fr_Version_Deviant_Value_Warn_Action {
            get {
                return ResourceManager.GetString("Max_Fr_Version_Deviant_Value_Warn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;, but should contains a value with a dot (&apos;x.x&apos; format)..
        /// </summary>
        internal static string Max_Fr_Version_Deviant_Value_Warn_Message {
            get {
                return ResourceManager.GetString("Max_Fr_Version_Deviant_Value_Warn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incompatible value of the &apos;framework_max_version&apos; parameter for the current project value of the  &apos;netstandard&apos; type .
        /// </summary>
        internal static string Max_Fr_Version_Reference_Conflict_Incomparable_Error_Cause {
            get {
                return ResourceManager.GetString("Max_Fr_Version_Reference_Conflict_Incomparable_Error_Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leads to a potential version conflict of targetFramework, as there is a reference to a project that has .
        /// </summary>
        internal static string Max_Fr_Version_Reference_Conflict_Warn_Message {
            get {
                return ResourceManager.GetString("Max_Fr_Version_Reference_Conflict_Warn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max acceptable
        ///version.
        /// </summary>
        internal static string Max_Fr_Version_Title {
            get {
                return ResourceManager.GetString("Max_Fr_Version_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;framework_max_version&apos; property of a .
        /// </summary>
        internal static string Max_Framework_Version_Deviant_Value_Error_Message {
            get {
                return ResourceManager.GetString("Max_Framework_Version_Deviant_Value_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove project &apos;.
        /// </summary>
        internal static string Message_On_Project_Remove_1 {
            get {
                return ResourceManager.GetString("Message_On_Project_Remove_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; from config file?.
        /// </summary>
        internal static string Message_On_Project_Remove_2 {
            get {
                return ResourceManager.GetString("Message_On_Project_Remove_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are project &apos;.
        /// </summary>
        internal static string Message_On_Project_Rename_1 {
            get {
                return ResourceManager.GetString("Message_On_Project_Rename_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; add and a project &apos;.
        /// </summary>
        internal static string Message_On_Project_Rename_2 {
            get {
                return ResourceManager.GetString("Message_On_Project_Rename_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; remove inside solution detected. .
        /// </summary>
        internal static string Message_on_Project_Rename_3 {
            get {
                return ResourceManager.GetString("Message_on_Project_Rename_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an empty project sample into config file for a project &apos;.
        /// </summary>
        internal static string Message_On_Project_Sample_Add_1 {
            get {
                return ResourceManager.GetString("Message_On_Project_Sample_Add_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;?.
        /// </summary>
        internal static string Message_on_Project_Sample_Add_2 {
            get {
                return ResourceManager.GetString("Message_on_Project_Sample_Add_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary action.
        /// </summary>
        internal static string Necessary_Action_Title {
            get {
                return ResourceManager.GetString("Necessary_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not detected required references.
        /// </summary>
        internal static string No_Detected_Req_References_Title {
            get {
                return ResourceManager.GetString("No_Detected_Req_References_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no required.
        /// </summary>
        internal static string No_Required_String {
            get {
                return ResourceManager.GetString("No_Required_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///of the project &apos;.
        /// </summary>
        internal static string Of_A_Project_String {
            get {
                return ResourceManager.GetString("Of_A_Project_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the &apos;framework_max_version&apos; property .
        /// </summary>
        internal static string Of_The_Fr_Max_Version_String {
            get {
                return ResourceManager.GetString("Of_The_Fr_Max_Version_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no any detected errors on export moment.
        /// </summary>
        internal static string On_Zero_Finded_Errors_Table_Report {
            get {
                return ResourceManager.GetString("On_Zero_Finded_Errors_Table_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no any detected warnings on export moment.
        /// </summary>
        internal static string On_Zero_Finded_Warnings_Table_Report {
            get {
                return ResourceManager.GetString("On_Zero_Finded_Warnings_Table_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference is matches with project name.
        /// </summary>
        internal static string One_Proj_Match_Error_Description {
            get {
                return ResourceManager.GetString("One_Proj_Match_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter .
        /// </summary>
        internal static string Parameter_Value {
            get {
                return ResourceManager.GetString("Parameter_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential version conflict!.
        /// </summary>
        internal static string Potential_Version_Conflict_Title {
            get {
                return ResourceManager.GetString("Potential_Version_Conflict_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problems not detected.
        /// </summary>
        internal static string Problems_Not_Detected {
            get {
                return ResourceManager.GetString("Problems_Not_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the typo in the project name.
        /// </summary>
        internal static string Proj_Name_Semantic_Warn_Action {
            get {
                return ResourceManager.GetString("Proj_Name_Semantic_Warn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; the semantic error is detected
        ///(expected: &apos;.
        /// </summary>
        internal static string Proj_Name_Semantic_Warn_Message {
            get {
                return ResourceManager.GetString("Proj_Name_Semantic_Warn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;; actual: &apos;.
        /// </summary>
        internal static string Proj_Name_Semantic_Warn_Message_1 {
            get {
                return ResourceManager.GetString("Proj_Name_Semantic_Warn_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project_Column_Title {
            get {
                return ResourceManager.GetString("Project_Column_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to following projects detected: &apos;.
        /// </summary>
        internal static string Project_Detection_Many {
            get {
                return ResourceManager.GetString("Project_Detection_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to following project detected: &apos;.
        /// </summary>
        internal static string Project_Detection_One {
            get {
                return ResourceManager.GetString("Project_Detection_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which not found.
        /// </summary>
        internal static string Project_Detection_Problem_Many {
            get {
                return ResourceManager.GetString("Project_Detection_Problem_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which not found.
        /// </summary>
        internal static string Project_Detection_Problem_One {
            get {
                return ResourceManager.GetString("Project_Detection_Problem_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the project on the correct spelling 
        ///of its name in the configuration file.
        /// </summary>
        internal static string Project_Match_Warning_Action {
            get {
                return ResourceManager.GetString("Project_Match_Warning_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A considered project is not found in the .
        /// </summary>
        internal static string Project_Match_Warning_Message {
            get {
                return ResourceManager.GetString("Project_Match_Warning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the rule on the correct
        ///spelling in the configuration file.
        /// </summary>
        internal static string Project_Not_Found_Warning_Action {
            get {
                return ResourceManager.GetString("Project_Not_Found_Warning_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is listed in the reference rule
        ///, but not found in the solution itself.
        /// </summary>
        internal static string Project_Not_Found_Warning_Message {
            get {
                return ResourceManager.GetString("Project_Not_Found_Warning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this projects.
        /// </summary>
        internal static string Project_Noun_Str_Many {
            get {
                return ResourceManager.GetString("Project_Noun_Str_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this project.
        /// </summary>
        internal static string Project_Noun_Str_One {
            get {
                return ResourceManager.GetString("Project_Noun_Str_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Add .
        /// </summary>
        internal static string Project_Offered_Action_Add_1 {
            get {
                return ResourceManager.GetString("Project_Offered_Action_Add_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in the config file?.
        /// </summary>
        internal static string Project_Offered_Action_Add_2 {
            get {
                return ResourceManager.GetString("Project_Offered_Action_Add_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Remove .
        /// </summary>
        internal static string Project_Offered_Action_Remove_1 {
            get {
                return ResourceManager.GetString("Project_Offered_Action_Remove_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from the config file?.
        /// </summary>
        internal static string Project_Offered_Action_Remove_2 {
            get {
                return ResourceManager.GetString("Project_Offered_Action_Remove_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config file (&apos;.
        /// </summary>
        internal static string Project_Problem_Place_Config_1 {
            get {
                return ResourceManager.GetString("Project_Problem_Place_Config_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _config_guard.rdg&apos;).
        /// </summary>
        internal static string Project_Problem_Place_Config_2 {
            get {
                return ResourceManager.GetString("Project_Problem_Place_Config_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution.
        /// </summary>
        internal static string Project_Problem_Place_Solution {
            get {
                return ResourceManager.GetString("Project_Problem_Place_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project sample.
        /// </summary>
        internal static string Project_Sample_List_Name {
            get {
                return ResourceManager.GetString("Project_Sample_List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  a project &apos;.
        /// </summary>
        internal static string Project_String {
            get {
                return ResourceManager.GetString("Project_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  contains the same type 
        ///of project in the template more than once.
        /// </summary>
        internal static string Project_Type_Copy_Error {
            get {
                return ResourceManager.GetString("Project_Type_Copy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference_Column_Title {
            get {
                return ResourceManager.GetString("Reference_Column_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve the contradiction in the rule.
        /// </summary>
        internal static string Reference_Match_Contrad_Warn_Action {
            get {
                return ResourceManager.GetString("Reference_Match_Contrad_Warn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminate rules duplicate.
        /// </summary>
        internal static string Reference_Match_Duplicate_Warn_Action {
            get {
                return ResourceManager.GetString("Reference_Match_Duplicate_Warn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve the contradiction in the rule.
        /// </summary>
        internal static string Reference_Match_Error_Action {
            get {
                return ResourceManager.GetString("Reference_Match_Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  contradict to a rule with eponymous reference .
        /// </summary>
        internal static string Reference_Match_Warn_Contrad_Message {
            get {
                return ResourceManager.GetString("Reference_Match_Warn_Contrad_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  duplicate a rule with eponymous reference .
        /// </summary>
        internal static string Reference_Match_Warn_Duplicate_Message {
            get {
                return ResourceManager.GetString("Reference_Match_Warn_Duplicate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string Reference_Names_Title {
            get {
                return ResourceManager.GetString("Reference_Names_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential
        ///version conflict.
        /// </summary>
        internal static string Reference_Potential_Version_Conflict_Type_Text {
            get {
                return ResourceManager.GetString("Reference_Potential_Version_Conflict_Type_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Reference_Required_Type_Text {
            get {
                return ResourceManager.GetString("Reference_Required_Type_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference sample.
        /// </summary>
        internal static string Reference_Sample_List_Table_Report_Name {
            get {
                return ResourceManager.GetString("Reference_Sample_List_Table_Report_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  reference .
        /// </summary>
        internal static string Reference_String {
            get {
                return ResourceManager.GetString("Reference_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference type.
        /// </summary>
        internal static string Reference_Type_Column_Title {
            get {
                return ResourceManager.GetString("Reference_Type_Column_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unacceptable.
        /// </summary>
        internal static string Reference_Unacceptable_Type_Text {
            get {
                return ResourceManager.GetString("Reference_Unacceptable_Type_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a required 
        ///one and.
        /// </summary>
        internal static string Req_Reference_Type {
            get {
                return ResourceManager.GetString("Req_Reference_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required reference not found!.
        /// </summary>
        internal static string Required_Reference_Not_Found_Title {
            get {
                return ResourceManager.GetString("Required_Reference_Not_Found_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check whether there are no read prohibits on .rdg files and root doesn&apos;t have prohibit on file creation.
        /// </summary>
        internal static string Rollback_File_Generation_Fail_Message {
            get {
                return ResourceManager.GetString("Rollback_File_Generation_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Rollback file generation error.
        /// </summary>
        internal static string Rollback_File_Generation_Fail_Title {
            get {
                return ResourceManager.GetString("Rollback_File_Generation_Fail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution config file parse.
        /// </summary>
        internal static string Solution_Config_File_String {
            get {
                return ResourceManager.GetString("Solution_Config_File_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of solution level.
        /// </summary>
        internal static string Solution_Level {
            get {
                return ResourceManager.GetString("Solution_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  For solution &apos;.
        /// </summary>
        internal static string Solution_Name_String {
            get {
                return ResourceManager.GetString("Solution_Name_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution .
        /// </summary>
        internal static string Solution_String {
            get {
                return ResourceManager.GetString("Solution_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that is specified in the &apos;all&apos; supertype at the same level.
        /// </summary>
        internal static string Supertype_All_Level {
            get {
                return ResourceManager.GetString("Supertype_All_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XLSX report ended with fail as the file is occupied by different process. 
        ///Close all Excel files and try again later.
        /// </summary>
        internal static string Table_Type_Export_Fail {
            get {
                return ResourceManager.GetString("Table_Type_Export_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XLSX export successfully ended.
        ///Open a folder with the generated report?.
        /// </summary>
        internal static string Table_Type_Export_Success {
            get {
                return ResourceManager.GetString("Table_Type_Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XLSX.
        /// </summary>
        internal static string Table_Type_Export_Title {
            get {
                return ResourceManager.GetString("Table_Type_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Framework.
        /// </summary>
        internal static string Target_Framework_Title {
            get {
                return ResourceManager.GetString("Target_Framework_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the specified 
        ///&apos;max_framework_version&apos; string for compliance with existing TFMs.
        /// </summary>
        internal static string TFM_Not_Found_Warn_Action {
            get {
                return ResourceManager.GetString("TFM_Not_Found_Warn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetFramework with the value 
        ///&apos;.
        /// </summary>
        internal static string TFM_Not_Found_Warn_Message {
            get {
                return ResourceManager.GetString("TFM_Not_Found_Warn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References in total.
        /// </summary>
        internal static string Total_References_Title {
            get {
                return ResourceManager.GetString("Total_References_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The considered project has 1 or more
        ///transitive references that duplicate the following direct references of the project: .
        /// </summary>
        internal static string Transit_Refs_Duplicate_Warn_Message {
            get {
                return ResourceManager.GetString("Transit_Refs_Duplicate_Warn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following transitive references
        /// have been found in this project:.
        /// </summary>
        internal static string Transit_Refs_Message {
            get {
                return ResourceManager.GetString("Transit_Refs_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start an export as the extension didn&apos;t detect any project references in this solution.
        /// </summary>
        internal static string Unable_To_Export_Message {
            get {
                return ResourceManager.GetString("Unable_To_Export_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is an 
        ///unacceptable one and.
        /// </summary>
        internal static string Unaccept_Reference_Type {
            get {
                return ResourceManager.GetString("Unaccept_Reference_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unacceptable.
        /// </summary>
        internal static string Unacceptable_String {
            get {
                return ResourceManager.GetString("Unacceptable_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  warning: It was not possible to verify the compliance of the references with the rules, as they were not detected at the time of state fixation. Make sure that the solution actually contains references between projects and perform a manual or automatic check along with the build.
        /// </summary>
        internal static string Unsuccessful_Checking_Rules_Warning {
            get {
                return ResourceManager.GetString("Unsuccessful_Checking_Rules_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  warning: It was not possible to parse data from the file &apos;.
        /// </summary>
        internal static string Unsuccessful_Config_File_Parse_Warning_1 {
            get {
                return ResourceManager.GetString("Unsuccessful_Config_File_Parse_Warning_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;. The rules from this file isn&apos;t included inside rules check.
        /// </summary>
        internal static string Unsuccessful_Config_File_Parse_Warning_2 {
            get {
                return ResourceManager.GetString("Unsuccessful_Config_File_Parse_Warning_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that the project has the correct version of its &apos;TargetFramework&apos;.
        /// </summary>
        internal static string Untyped_Warn_Action {
            get {
                return ResourceManager.GetString("Untyped_Warn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to check the version of &apos;TargetFramework&apos; for the considered project,
        ///cause the program could not get the correct value for this property from the .csproj file.
        /// </summary>
        internal static string Untyped_Warn_Message {
            get {
                return ResourceManager.GetString("Untyped_Warn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a value &apos;.
        /// </summary>
        internal static string Value_String {
            get {
                return ResourceManager.GetString("Value_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  version &apos;.
        /// </summary>
        internal static string Version_String {
            get {
                return ResourceManager.GetString("Version_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning levels.
        /// </summary>
        internal static string Warning_Level_Title {
            get {
                return ResourceManager.GetString("Warning_Level_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning type.
        /// </summary>
        internal static string Warning_Type_Title {
            get {
                return ResourceManager.GetString("Warning_Type_Title", resourceCulture);
            }
        }
    }
}
