//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefDepGuard.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefDepGuard.Console.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check state on accordance to config file rules.
        /// </summary>
        internal static string Check_Rules_Title {
            get {
                return ResourceManager.GetString("Check_Rules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     - Error: It was not possible to parse data from the.
        /// </summary>
        internal static string Config_File_Syntax_Error {
            get {
                return ResourceManager.GetString("Config_File_Syntax_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  config file.
        ///Check this file on existence and no syntax errors.
        /// </summary>
        internal static string Config_File_Syntax_Error_1 {
            get {
                return ResourceManager.GetString("Config_File_Syntax_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config files state parse.
        /// </summary>
        internal static string Config_Files_State_Parse_Title {
            get {
                return ResourceManager.GetString("Config_Files_State_Parse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRORS:.
        /// </summary>
        internal static string Errors_String_Title {
            get {
                return ResourceManager.GetString("Errors_String_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: .
        /// </summary>
        internal static string File_String {
            get {
                return ResourceManager.GetString("File_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are any problems found during current check: (errors - .
        /// </summary>
        internal static string Find_Problems_on_Check {
            get {
                return ResourceManager.GetString("Find_Problems_on_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; warnings - .
        /// </summary>
        internal static string Find_Problems_On_Check_1 {
            get {
                return ResourceManager.GetString("Find_Problems_On_Check_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.
        /// </summary>
        internal static string Global_Config_File {
            get {
                return ResourceManager.GetString("Global_Config_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello from the console RefDepGuard! Please wait while the full check ends.
        /// </summary>
        internal static string Hello_Message {
            get {
                return ResourceManager.GetString("Hello_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     - Error: It was not possible to parse the data from the .sln file of the root directory of the solution.
        ///Make sure that the application is running in the correct root folder containing the .sln file of the same name.
        /// </summary>
        internal static string Invalid_Directory_Error {
            get {
                return ResourceManager.GetString("Invalid_Directory_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no any find problems during current check.
        /// </summary>
        internal static string No_Find_Problems_On_Check {
            get {
                return ResourceManager.GetString("No_Find_Problems_On_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        internal static string Project_String {
            get {
                return ResourceManager.GetString("Project_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - Error: It was not possible to verify the compliance of the references with the rules, as they were not detected at the time of fixing the status of the solution.
        ///Make sure that the solution actually contains references between projects and perform a manual or automatic check along with the build.
        /// </summary>
        internal static string Refs_Not_Found_Error {
            get {
                return ResourceManager.GetString("Refs_Not_Found_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution.
        /// </summary>
        internal static string Solution_Config_File {
            get {
                return ResourceManager.GetString("Solution_Config_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are following projects and references between them:.
        /// </summary>
        internal static string Solution_State_Parse_Start_Message {
            get {
                return ResourceManager.GetString("Solution_State_Parse_Start_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution state parse.
        /// </summary>
        internal static string Solution_State_Parse_Title {
            get {
                return ResourceManager.GetString("Solution_State_Parse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for solution:.
        /// </summary>
        internal static string Solution_Title {
            get {
                return ResourceManager.GetString("Solution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNINGS:.
        /// </summary>
        internal static string Warnings_String_Title {
            get {
                return ResourceManager.GetString("Warnings_String_Title", resourceCulture);
            }
        }
    }
}
